server:
  port: 8101

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/userdb?options=-c%20TimeZone%3DAsia/Kolkata
    username: postgres
    password: postgres
    hikari:
      connectionInitSql: "SET TIME ZONE 'Asia/Kolkata'"


  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  flyway:
    enabled: true
    locations: classpath:db/migration

management:
  endpoints:
    web:
      exposure:
        include: health,info
