server:
  port: 8080
spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      default-filters:
        - RemoveRequestHeader=Cookie
      globalcors:
        add-to-simple-url-handler-mapping: true 
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders: "*"
            allowCredentials: false
      routes:
        - id: user-service
          uri: http://localhost:8101
          predicates: [ Path=/api/users/** ]
          filters: [ StripPrefix=1 ]
        - id: user-service-drivers
          uri: http://localhost:8101
          predicates: [ Path=/api/drivers/** ]
          filters: [ StripPrefix=1 ]
        - id: order-service
          uri: http://localhost:8102
          predicates: [ Path=/api/orders/** ]
          filters: [ StripPrefix=1 ]
        - id: tracking-service-http
          uri: http://localhost:8106
          predicates: [ Path=/api/tracking/** ]
          filters: [ StripPrefix=1 ]
        - id: tracking-service-ws
          uri: http://localhost:8106
          predicates: [ Path=/ws/** ]
        - id: routing-adapter
          uri: http://localhost:8110
          predicates:
            - Path=/api/geo/**
          filters:
            - StripPrefix=1
  data:
    redis:
      host: localhost
      port: 6379

management:
  endpoints:
    web:
      exposure:
        include: health,info
